# Generated by Django 4.2.7 on 2024-01-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_verified_email_emailverifcation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailVerifcation',
            new_name='EmailVerification',
        ),
        migrations.RenameField(
            model_name='emailverification',
            old_name='experation',
            new_name='expiration',
        ),
    ]
