# Generated by Django 4.2.7 on 2024-01-30 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_quatity_basket_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
